python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10/epoch_100_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10/epoch_200_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10/epoch_300_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10/epoch_400_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10/epoch_500_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_rot10/epoch_600_weights.pth
