python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn/epoch_100_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn/epoch_200_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn/epoch_300_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn/epoch_400_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn/epoch_500_weights.pth

python tools/test_nop.py configs/trainval/tad/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn.py workdir/baseline_ssd_randomcrop_sgdr_fps25_flip_nocpn/epoch_600_weights.pth
